adjust-brighness: log file check, updated logging format.

diff --git a/adjust-brightness b/adjust-brightness
--- a/adjust-brightness
+++ b/adjust-brightness
@@ -9,16 +9,29 @@
 #
 # e.g. xrandr --output LVDS-1 --brightness 0.7
 # sets brightness for LVDS-1 to 70%
-# WARNING
-# this script is tailored to my specific monitors and environment setup.
-# Please identify and/or place your edits using your monitor name(s)
 
-
+PROGNAME=$(basename $0)
 CURRENTDATE=$(date +"%x %r %Z") 
 MONITORLIST=$(xrandr --listmonitors | cut -d ' ' -f6)
 LEFTMONITOR=$(xrandr --listmonitors | head -n 2 | cut -d ' ' -f6)
 RIGHTMONITOR=$(xrandr --listmonitors | tail -n 1 | cut -d ' ' -f6)
 LOGFILE="$HOME/scripts/log/adjust-brightness.log"
+
+# check for log file, prompt for creation
+if [[ ! -f ${LOGFILE} ]]; then
+    echo "\"${LOGFILE}\" does not exist."
+    read -p "Would you like to create a new log file? (y/n): "
+    case ${REPLY} in
+        y)
+            /usr/bin/touch ${LOGFILE}
+            [[ $? -eq 0 ]] || ( echo "${LINENO}: ERROR: creating log file failed." && exit 1 )
+            echo -e "\nCreated ${LOGFILE}"
+            ;;
+        *)
+            echo
+            ;;
+    esac
+fi
 
 # output list of connected displays
 echo -e "\nConnected monitors: $MONITORLIST\n"
@@ -36,7 +49,7 @@ case ${REPLY} in
         sleep 1
         xrandr --output $RIGHTMONITOR --brightness $REPLY
 
-        echo -e "Monitor brightness set to "${REPLY}" on "${CURRENTDATE}"\n" 2>&1 | tee -a $LOGFILE
+        echo -e "${PROGNAME}[$$]: Monitor brightness set to "${REPLY}" on "${CURRENTDATE}"" 2>&1 | tee -a $LOGFILE >/dev/null
         echo -e "done.\n"
 
         ;;
